### ISSUE TITLE
Installation: how to install imageio-ffmpeg when using python 3.6 ?

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-video#43]
Hi,

For some reason, imageio-ffmpeg is not in the requirements of `setup.py`.

So I ran `pip install imageio-ffmpeg`. The installation didn't show any errors but when importing `imageio_ffmpeg` I had a `ModuleNotFoundError`.

On the contrary, with python 3.7, I was able to install simply imageio-ffmpeg using the same command.

I fixed it by installing it via conda : `conda install -c conda-forge imageio-ffmpeg `

**Comment by hbredin** [comment]
I believe `imageio-ffmpeg` is *not* needed. `imageio` [is](https://github.com/pyannote/pyannote-video/blob/40e65bd4660456dfeafe68246db8da48ae6021da/pyannote/video/video.py#L120) , though.

**Comment by PaulLerner** [comment]
Oh ok, then I had a problem with `imageio.plugins.ffmpeg.download()` and understood the error messages incorrectly.

I solved it by downgrading `imageio` to version `2.4.1` thanks to [this guy](https://github.com/artyshko/smd/issues/3#issuecomment-475963236) (only I used conda instead of pip).

**Comment by PaulLerner** [comment]
> I believe `imageio-ffmpeg` is _not_ needed. `imageio` [is](https://github.com/pyannote/pyannote-video/blob/40e65bd4660456dfeafe68246db8da48ae6021da/pyannote/video/video.py#L120) , though.

You might want to update this code as `imageio.plugins.ffmpeg.download()` has been deprecated (as I've said above I had to downgrade imageio).
When running the demo :
```
pyannote-face.py demo ../pyannote-data/TheBigBangTheory.mkv \
                       ../pyannote-data/TheBigBangTheory.track.txt \
                       ../pyannote-data/TheBigBangTheory.track.mp4
```
I got 
```py
Traceback (most recent call last):
  File "/people/lerner/anaconda3/envs/pyannote/bin/pyannote-face.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyannote.video==1.6.3+1.g40e65bd.dirty', 'pyannote-face.py')
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/pyannote.video-1.6.3+1.g40e65bd.dirty-py3.7.egg/EGG-INFO/scripts/pyannote-face.py", line 481, in <module>
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/pyannote.video-1.6.3+1.g40e65bd.dirty-py3.7.egg/EGG-INFO/scripts/pyannote-face.py", line 401, in demo
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/moviepy-0.2.3.4-py3.7.egg/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/people/lerner/anaconda3/envs/pyannote/lib/python3.7/site-packages/imageio-2.6.1-py3.7.egg/imageio/plugins/ffmpeg.py", line 40, in download
    "imageio.ffmpeg.download() has been deprecated. "
RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'
```

**Comment by hbredin** [comment]
Can you make a pull request adding (and using) this new dependency?
