### ISSUE TITLE
Problem running pyannote on 1080 resolution videos

### ISSUE THREAD

**Issue by rishabhjain16** [pyannote/pyannote-video#48]
#### I am getting the following error when I run the script

!pyannote-face.py demo 4_1080.mp4 \ 4_1080.track.txt \ 4_1080.track.mp4  

4_1080 - contains a 2-minute short clip of Friends tv show episode in 1080p resolution 

#### I am getting the following error: 

[MoviePy] >>>> Building video 4_1080.track.mp4
[MoviePy] Writing audio in 4_1080.trackTEMP_MPY_wvf_snd.mp3
  0%|                                                  | 0/3394 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/audio/io/readers.py", line 190, in get_frame
    result[in_time] = self.buffer[indices]
IndexError: index -100001 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyannote-face.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyannote.video==1.6.3+6.g036fe5b.dirty', 'pyannote-face.py')
  File "/usr/local/lib/python3.6/dist-packages/setuptools-47.1.1-py3.6.egg/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-47.1.1-py3.6.egg/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/pyannote.video-1.6.3+6.g036fe5b.dirty-py3.6.egg/EGG-INFO/scripts/pyannote-face.py", line 481, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyannote.video-1.6.3+6.g036fe5b.dirty-py3.6.egg/EGG-INFO/scripts/pyannote-face.py", line 412, in demo
  File "<decorator-gen-765>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-764>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-763>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/video/VideoClip.py", line 317, in write_videofile
    verbose=verbose, progress_bar=progress_bar)
  File "<decorator-gen-787>", line 2, in write_audiofile
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/audio/AudioClip.py", line 213, in write_audiofile
    progress_bar=progress_bar)
  File "<decorator-gen-784>", line 2, in ffmpeg_audiowrite
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/audio/io/ffmpeg_audiowriter.py", line 170, in ffmpeg_audiowrite
    progress_bar=progress_bar):
  File "/usr/local/lib/python3.6/dist-packages/tqdm-4.46.0-py3.6.egg/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/audio/AudioClip.py", line 84, in generator
    fps=fps, buffersize=chunksize)
  File "<decorator-gen-786>", line 2, in to_soundarray
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/audio/AudioClip.py", line 130, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<decorator-gen-724>", line 2, in get_frame
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/Clip.py", line 137, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/Clip.py", line 189, in <lambda>
    return self.fl(lambda gf, t: gf(t_func(t)), apply_to,
  File "<decorator-gen-724>", line 2, in get_frame
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/audio/io/AudioFileClip.py", line 78, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "/usr/local/lib/python3.6/dist-packages/moviepy-0.2.3.4-py3.6.egg/moviepy/audio/io/readers.py", line 202, in get_frame
    result[in_time] = self.buffer[indices]
IndexError: index -100001 is out of bounds for axis 0 with size 0

**Comment by tachikoma777** [comment]
Hi, i got same error, did u figure it out?

**Comment by tachikoma777** [comment]
#audio_clip = AudioFileClip(filename)
    #clip = video_clip.set_audio(audio_clip)
    clip = video_clip

this works for me, --height=<n_pixels> may also needed if height is not 400
